export { default as AssemblyModals } from './Assembly/Modals.vue'
export { default as ChoosDroneModals } from './ChoosDrone/Modals.vue'
export { default as DataParsingModals } from './DataParsing/Modals.vue'
export { default as ReportModals } from './Report/Modals.vue'
export { default as RoutingModals } from './Routing/Modals.vue'
